### ISSUE TITLE
Opening link overwrites previous link

### ISSUE THREAD

**Issue by seandaopanel** [relaycc/relay#10]
The "View on [Site]" buttons for profiles and the links to the sites have strange behavior. They will open a new tab. Then subsequent clicks on other "View on Site" buttons will overwrite the site in that tab. 

I want to be able to click on 10 links and have 10 new tabs open. 

Also right click on the "View on Site" buttons does not work.

**Comment by BrianS111** [comment]
https://github.com/relaycc/relay/pull/30

Got ya here except for the right click thing. I Didn't even realize that was part of the issue until now. If its still a prob we can make a new issue and solve it
