### ISSUE TITLE
Change message button color to reflect `handle` existence in supabase

### ISSUE THREAD

**Issue by seanrelay** [relaycc/relay#108]
# Guidelines

* This issue describes an improvement to an _existing feature_.
* This issue is _descriptive_ and _declarative_, but not _imperative_. It describes the end goal but does not prescribe actions.
* This issue is _not a duplicate_.

# Details

### Describe the improvement.
For the "Message" button on each card, keep the exact same functionality but have the button be a grey color if they have an EMTPY value for handle in the database.

### Describe the use case.
The UX of "Message" when 95% of apps aren't connected to message yet is bad. 

So on the home page, XMTP, Lens, and Lenstube will be green to message. This is a pretty clear call to action for apps to get connected with us. And if they click the grey button, they get the same-as-current functionality to message with relaycc.eth in Receiver. 

### Describe alternatives you've considered.

# Development

**Comment by killthebuddh4** [comment]
This is done.
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/100799178/212500065-83e03ce1-6ec2-4811-8437-7192cdd2fbe6.png">
