### ISSUE TITLE
Two unique card types + user edits

### ISSUE THREAD

**Issue by seanrelay** [relaycc/relay#15]
Profile Pic card: A single unique card would include a picture of an NFT I own (or user-uploaded image if it's easier) and a 140 character bio the user writes.

Web2 Social Card: A single unique card would include user-configured profile links. 
Twitter, Discord, Telegram, Email, etc. 

User config edits: 
When I go to my own profile, Relay will enable certain edit-ability of the cards.
Examples: Update the web2 links, re-order my cards, set my Primary picture and 140 character bio on Profile card, add on-Hover pictures to other App cards.

**Comment by seandaopanel** [comment]
I envision a top row of these 6 cards: Profile Pic card, Relay card, web2 Social Card, and 3 NFTs that they select to show.

**Comment by seandaopanel** [comment]
The profile pic card should have a large "message" button that opens Receiver, and remove "send a message" from the app cards.
