### ISSUE TITLE
relay.cc --> relay.cc/conversations

### ISSUE THREAD

**Issue by seanrelay** [relaycc/relay#17]
relay.cc home page should be the conversation list that's currently at relay.cc/conversation.

Add a button in the header near connect wallet that links to the user's profile with text "Web3 Profile"
[TODO: think of Relay specific name instead of Profile. In the style of web3 footprint, web3 crossroads, data backpack]

**Comment by seandaopanel** [comment]
Alternately, we put the 20 most recent conversation cards at the top of the page, and then show app cards under that section. 

I like this idea a bit better because the home page keeps the current look and won't be empty for first time visitors.

**Comment by killthebuddh4** [comment]
Closed by a28e1fbafba987315be87168af63e1889bbe096d

**Comment by killthebuddh4** [comment]
Actually just switched the routing part, did not do the add'l items.

**Comment by killthebuddh4** [comment]
@seandaopanel What do you think about https://github.com/relaycc/relay/issues/19#issuecomment-1266152623 ?

**Comment by seandaopanel** [comment]
I think I replied elsewhere, 👍

**Comment by seanrelay** [comment]
Reverting this change is in #51, can be closed.
