### ISSUE TITLE
Social + Landing page links

### ISSUE THREAD

**Issue by seandaopanel** [relaycc/relay#18]
We need links to try.relay.cc , twitter, mirror, and discord. @killthebuddh4 These could be small icons in the header, or we introduce a footer section. 
I'm strongly in favor of them in the header, because we want 100% of relay.cc first visits to translate into a twitter follow or discord join. 
I'm thinking of an "About Relay" button, that on hover shows these 4 icon links. @BrianS111 could do.

**Comment by BrianS111** [comment]
![F510F254-341A-4CE7-8445-925249863386](https://user-images.githubusercontent.com/81312527/193663704-7b595141-6a16-4e47-bd81-1c481d779424.jpeg)
Since seeing the website I've always thought in this empty header space it would be a good idea to have the name of the profile you navigated to. like a "You are on that page" type thing. Things barely change when navigating through different profiles. I can put them in the header, make a social dropdown, or build a footer that has them in.

**Comment by BrianS111** [comment]
Wherever you want me to put them, I'm down. I can also get creative and come up with something

**Comment by killthebuddh4** [comment]
Here's the spec:

* replace the input in the top left with logo links
* logos should be relay, twitter, mirror, and discord
* the logo should be flat black (preferable SVG)
* As far as I know we don't have a flat black Relay logo, getting this is part of this ticket
* I will figure out what to do with the input field in a future commit

**Comment by seandaopanel** [comment]
The search input field is useful functionality, why delete? We want to expose to lookup / discovery functionality for Relay profiles

We can center it for now.

**Comment by seandaopanel** [comment]
+ github link
@BrianS111 I liked the look the of old social links section that was in the header/footer of relay.cc, with the purple links. The same links but flat black would be good.

**Comment by BrianS111** [comment]
![8133D4BB-629A-4192-9FE2-00DE09D1314A_4_5005_c](https://user-images.githubusercontent.com/81312527/193692429-40400d81-7435-4ad1-9acd-60b653d4f557.jpeg)

I was planning on using this guy for the ticket, but I can do whatev

**Comment by BrianS111** [comment]
Oh I know what you are talking about...

**Comment by BrianS111** [comment]
1 sec

**Comment by BrianS111** [comment]
We didnt

**Comment by BrianS111** [comment]
> * github link
>   @BrianS111 I liked the look the of old social links section that was in the header/footer of relay.cc, with the purple links. The same links but flat black would be good.

I'm actually having a hard time finding the image or a reference to it but I know what you're talking about. ( logo | logo | logo | logo ) Bright purple background etc? That with black background and purple font? I'll go with the base specs first, then we can work up some mockups or something for a cool design

**Comment by seandaopanel** [comment]
@BrianS111 try this one 
![blacklogo11](https://user-images.githubusercontent.com/102389629/193696781-44c3fa95-9cc6-4ed2-a872-0d0d83374dbb.svg)

**Comment by killthebuddh4** [comment]
Ok so for the input:

* on desktop, make the input flow to fill the space in the navbar like this
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/100799178/193696623-e68a46f7-799b-44bb-966f-dc633364d0a2.png">

* on mobile, the current flow should work, but with the social icons and the connect button sharing the first line. Update here if you can't make the icons and the connect button fit on a single line

How's that sound?

**Comment by seandaopanel** [comment]
yea sounds good.

**Comment by seandaopanel** [comment]
<img width="1728" alt="Screen Shot 2022-10-03 at 7 33 16 PM" src="https://user-images.githubusercontent.com/102389629/193709601-871b24f2-56ee-441c-b91d-c7b767ea5ea0.png">
they center the header elements with a max width to the nav bar

**Comment by BrianS111** [comment]
https://user-images.githubusercontent.com/81312527/193733111-09a11be0-bef9-4fe5-a625-29f70f56cc64.mov

Like this? If not where do I go from here

**Comment by killthebuddh4** [comment]
> AFACBB16-FD7E-45B1-BA7A-9AD066F6C122.mov
> 
> Like this? If not where do I go from here

* In the narrower views, the social icons and the connect button should both be on the first line, the input on on the second.
* I think maybe give the input a max width of like 75% of what it is in the video you posted and have margin-left auto. Right now the social icons and the input being right next to each other looks kind of weird.
* The input should have a search icon

**Comment by seandaopanel** [comment]
If we can push these soon there's a few posts I want to make about this

**Comment by BrianS111** [comment]
I'm working on it right now. Debugging is slightly tough as I haven't been using tailwind lately

**Comment by BrianS111** [comment]
https://user-images.githubusercontent.com/81312527/193936155-71bd8a4f-076a-4021-b52f-b37cacbb0ad5.mov

How does this look?

**Comment by BrianS111** [comment]
Maybe a little more adjusting in the smallest view?

**Comment by BrianS111** [comment]
I pushed a PR with the video shown above

**Comment by killthebuddh4** [comment]
> F28C3388-43A0-4FB4-A693-8FA8C3D5DC8D.mov 
> How does this look?

This looks good! See my comment in the PR, it looks like the PR is an older version.

**Comment by killthebuddh4** [comment]
Ah my bad I didn't watch the whole video. @BrianS111 in the video the connect button and social icons are on the **second line**, they should be on the first line.

**Comment by BrianS111** [comment]
https://user-images.githubusercontent.com/81312527/193952405-cb1f8399-bf85-40a8-a024-5ad30b85af26.mov

**Comment by seanrelay** [comment]
@killthebuddh4 referring back to this and the mockup you made. I think the github logo looks good. I think the text looks iffy, more in your face than the subtle icons. But maybe that's good.
https://tableland.xyz/ looks fine. 

https://relay-64so0lzmh-relaycc.vercel.app/ has a unique 3d effect on scroll haha
