### ISSUE TITLE
relay.cc functions on mobile

### ISSUE THREAD

**Issue by seandaopanel** [relaycc/relay#19]
I'll be in Bogota and showing both relay.cc/conversations and relay.cc/u/seanwbren.eth *a lot*. They need to be functional on mobile, which would be changing how to the on-hover links get shown and possibly more improvements. 

Related to https://github.com/relaycc/relay/issues/17 (relay.cc shows conversations) and https://github.com/relaycc/landing/issues/28 (I'm hoping Dynamic login flow will work better for mobile than Rainbow)

**Comment by BrianS111** [comment]
Part A of this issue is an easy one. I got ya

**Comment by killthebuddh4** [comment]
For the mobile navbar I suggest we implement a flow that's basically the same as on https://sound.xyz

https://user-images.githubusercontent.com/100799178/193699020-9365f0a3-1404-45e6-b8bf-400ae3bd012f.mov

@seandaopanel What do you think?

**Comment by seandaopanel** [comment]
> 

that flow looks good

**Comment by BrianS111** [comment]
Is this still an issue? If so, what needs to be done to meet the goal

**Comment by killthebuddh4** [comment]
I'm going to close this as done for now, there's definitely mobile stuff that needs doing, but we can't create specific tickets for them as we go.
