### ISSUE TITLE
When you navigate to a profile, the page title should show their handle.

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/relay#2]

**Comment by BrianS111** [comment]
![CB6723B8-C12A-4C38-AC8E-5010865E8DE6_4_5005_c](https://user-images.githubusercontent.com/81312527/194196201-ed3db8f9-2793-47c5-af8c-079f7595ccc1.jpeg)

Do you mean it should only say vdp.eth in the title section after searching for vdp.eth? without the https:// etc??

**Comment by seandaopanel** [comment]
Yes that sounds correct.

**Comment by BrianS111** [comment]
I just noticed that when you sign in and your recent conversations are listed, after clicking one it shows the address instead of ens name. That's prob what this issue is about. If not, another issue could be created to solve that if it's unintended

**Comment by killthebuddh4** [comment]
The first guess was the correct one. When you navigate to https://relay.cc/u/SOMETHING, the title of the page in the tab should be SOMETHING.

**Comment by seandaopanel** [comment]
And for relay.cc it should just say Relay

**Comment by BrianS111** [comment]
Are we sure we want to break the consistency and flow of things though? If the title matches the profile you are on I feel It should be that way with relaycc.eth. I think the title should say Relay in a landing page scenario. Or 'Relay - 'insert epic statement here"

**Comment by killthebuddh4** [comment]
> Are we sure we want to break the consistency and flow of things though? If the title matches the profile you are on I feel It should be that way with relaycc.eth. I think the title should say Relay or 'Relay - 'insert epic statement here" in a landing page scenario

On `https://relay.cc/u/relaycc.eth` the title should be "relaycc.eth". On `https://relay.cc` the title should be "Relay", does that make sense?

**Comment by BrianS111** [comment]
Yeah, I was mixing the two, lol.
