### ISSUE TITLE
Messages on DM have issues

### ISSUE THREAD

**Issue by Aaron-EE** [relaycc/relay#300]
Issue 1: Sometimes the messages under the first message are missaligned.  

Issue 2:  '11:30 AM' is longer then 'Today' for eg and gets pushed into two rows, which makes our one line messages look different hight depending on when they were recieved or sent. 

We should get all messages lined up vertically, and the hight should only depend on the message content eg.: how many row it is, and not the time of sending

<img width="681" alt="image" src="https://user-images.githubusercontent.com/66436916/214541773-b86b79bc-13d3-4764-b033-42d2bb877b2d.png">

On the X axis the texts are getting missaligned, for another reason. As the length of the recieved time changes, it can push the messages aside

<img width="471" alt="image" src="https://user-images.githubusercontent.com/66436916/214547146-2bde0729-cf7f-48a3-8c55-2e76b0823950.png">

Issue 3:The primary colored blue name should be the users name, not the other chat partners. There is two types `ENSName.EnsNameMonofontLg` components  one is blue one is black, probably they are just used the wrong way around in DM page 

Its backwards 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/66436916/214547890-3726b8d7-c338-4681-9e3e-c0c24139a9f8.png">

**Comment by CsillagK** [comment]
Issue 1, Issue 2: done (look at the hovered one, I turned on the visibility for testing only)
<img width="670" alt="Screenshot 2023-01-25 at 19 58 09" src="https://user-images.githubusercontent.com/122450390/214657715-fe14713a-47c5-459b-99a8-b3a8edad61cb.png">

Issue3: done, changed it on the DMpage
