### ISSUE TITLE
Conversations list not populated

### ISSUE THREAD

**Issue by andrewvdp** [relaycc/relay#349]
### Describe the bug. Include a video.
https://www.loom.com/share/8bfb8042d9ca435b8e359e07661f907b
### What is the expected behavior?
If I am a current user with messages on the XMTP network I should see those messages in my conversation list
### What is the actual behavior?
All of my active messages are showing up in the message request section
### How can you reproduce the bug?
Be a user on the XMTP network and open receiver to view the conversations page

**Comment by killthebuddh4** [comment]
@andrewvdp This is working correctly, any conversation that has not been accepted or ignored is considered a request. Because this feature is brand new, existing conversations are requests.
