### ISSUE TITLE
Header links don't link to anything

### ISSUE THREAD

**Issue by andrewvdp** [relaycc/relay#350]
### Describe the bug. Include a video.
https://www.loom.com/share/c793e41af21b424d94701c4e73a443e0
### What is the expected behavior?
When I click on a link in the header it should link to something.
### What is the actual behavior?
The links pop up with a browser alert
### How can you reproduce the bug?
Click on a header link.

**Comment by killthebuddh4** [comment]
This was merged but I accidentally created a dupe issue for this.
