### ISSUE TITLE
Docs and careers link don't link anywhere

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/relay#356]
### Describe the bug. Include a video.

The docs and the careers buttons don't do anything.

https://www.loom.com/share/3d3de1fe3b24412bb80aa32b2a9fbe8d

### What is the expected behavior?

They should do something, not sure what.

### What is the actual behavior?

They do nothing.

### How can you reproduce the bug?

Go to https://relay.cc, navigate to footer, click the buttons in question.

**Comment by seanrelay** [comment]
@mmmarcusb is updating the docs now. 
So docs should link to: https://docs.relay.cc/about/
Careers should link to: https://jobs.lever.co/relay

**Comment by seanrelay** [comment]
@killthebuddh4 @andrewvdp can we update the careers page to have our open Python/LLM role instead of the Frontend Dev. 
Also we need to talk about what language we want for Bridge.
