### ISSUE TITLE
Receiver UX: Time stamps + Message Inputs

### ISSUE THREAD

**Issue by oswidandesign** [relaycc/relay#359]
### Describe the bug. Include a video.

https://loom.com/share/355510de91984dc688e365ab03862daf

### What is the expected behavior?
https://www.figma.com/file/oeHqO9qLCkz7SYb73J5Qx4/ReceiverV0-Design-File?node-id=972%3A22833&t=fDWtnLmUAhl4AlX7-4

### What is the actual behavior?
![Screenshot 2023-01-31 at 3 51 13 PM](https://user-images.githubusercontent.com/120046997/215910072-e0231800-ffbd-4f0c-82d9-855fced60343.png)

### How can you reproduce the bug?
Visit the DM page

**Comment by killthebuddh4** [comment]
@matejcsok-ee @Aaron-EE Let me know if you guys are able to view the loom in this issue. For some reason when I try to view it there's just a black screen.

**Comment by matejcsok-ee** [comment]
> @matejcsok-ee @Aaron-EE Let me know if you guys are able to view the loom in this issue. For some reason when I try to view it there's just a black screen.

it is good for me

**Comment by killthebuddh4** [comment]
One of the other issues included the right-alignment for timestamps, so that's done already.
