### ISSUE TITLE
For profiles that need to be activated by the user, we should not link to 404s

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/relay#36]
* For certain apps (e.g. Giveth), the profile link doesn't work until the profile is created by the user.
* In the Giveth case, the profile link 404s
* When possible (like with Giveth), we should detect broken links and handle them
* How should we handle broken links?
* Do different sites need to be handled differently? Do we just show something on our end that says "profile doesn't exist"?

**Comment by seandaopanel** [comment]
We could grey out the whole card and make the profile link not clickable.

There's some sites like gitcoin that have user-made handles, which we can link out to if the user configures it. 

Then there's sites like Giveth and 101 that require the user to sign up first, and then use the address as a standard route.

**Comment by killthebuddh4** [comment]
* When a user clicks the link button, instead of just jumping directly there, add a check for a working link, something like:
   * `fetch(theLink)`
   * `if (status !== 200) doOneThing();`
   *  `else linkToPage()`

**Comment by killthebuddh4** [comment]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/100799178/197041503-606785f0-71bd-4030-b252-1cc77747831a.png">

* When the user clicks the link, and the link doesn't work, show this error message
* The error message should stay visible for like (5-10 ?) seconds
* text should be red, opacity 0.8
* the text should fade in and fade out
