### ISSUE TITLE
Message accept/ignore not working

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/relay#365]
### Describe the bug. Include a video.

This one needs to be documented/reproduced but it seems that the accept/ignore feature is not working at all for @seanrelay. My understanding is that screen just doesn't do anything.

### What is the expected behavior?

TBD

### What is the actual behavior?

TBD

### How can you reproduce the bug?

TBD

**Comment by killthebuddh4** [comment]
@seanrelay Please add a Loom here of the behavior you experience.

**Comment by seanrelay** [comment]
It's working for me now

**Comment by seanrelay** [comment]
And now it isn't: https://www.loom.com/share/ed1408f554cf49249603f99f29c26ab5

**Comment by killthebuddh4** [comment]
@matejcsok-ee I'm not 100% sure what's going on in the shared video, but I think it might have something to do with the following:

* Before we call `write` we should probably `read` the existing value. If we don't `read` before we `write` we could end up with stale data. Reading then writing won't completely solve the problem, but I think it will make it less bad.
