### ISSUE TITLE
101.xyz link is  broken

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/relay#378]
### Describe the bug. Include a video.

The 101.xyz link is broken

https://www.loom.com/share/9ab5e7f637444e00beff6507ba1bd735

### What is the expected behavior?

101.xyz link goes to 101.xyz

### What is the actual behavior?

The link is broken.

### How can you reproduce the bug?

Go to relay.cc/identity, click on the "Visit" button on the 101.xy card.

**Comment by seanrelay** [comment]
fixed in supabase
