### ISSUE TITLE
Adding functionality to the icon in the search bar

### ISSUE THREAD

**Issue by BrianS111** [relaycc/relay#38]
![4DE674F3-F09C-4DC5-995D-2D1016A1F376_4_5005_c](https://user-images.githubusercontent.com/81312527/194625149-ba5dab2c-159d-463d-8f4e-7a6c050d28cd.jpeg)
@killthebuddh4 @andrewvdp Right now there is no functionality to the icon in the search bar. Do we want to have the same functionality as hitting 'Enter' or is it there for aesthetics?

**Comment by killthebuddh4** [comment]
Good question. I just checked Sound, OpenSea, Rarible, Lenster, and Snapshot, and it doesn't do anything on any of those sites. To me that's enough data to close this one out.
