### ISSUE TITLE
Ignored Messages CRASHES reciever

### ISSUE THREAD

**Issue by oswidandesign** [relaycc/relay#385]
### Describe the bug. Include a video.

https://www.loom.com/share/967733d0589b4c9e92d3c72a19be00eb

### What is the expected behavior?

Ignored Messages should un-collapse when that tab is clicked. 

### What is the actual behavior?

Clicking Ignored Messages tab crashes receiver. 

### How can you reproduce the bug?

Clicking Ignored Messages

**Comment by seanrelay** [comment]
I tried but I can't reproduce this bug
