### ISSUE TITLE
Conversation list scroll level is remembered after entering and backing from a DM

### ISSUE THREAD

**Issue by seanrelay** [relaycc/relay#386]
### Describe the bug. Include a video.
https://www.loom.com/share/e37f034bea34409bbf59a52cf54ec07c

### What is the expected behavior?
If I'm in my conversation list, and enter into a 1:1 DM with someone, when I go back I should still be at the same scroll level.

### What is the actual behavior?
I'm brought back to the top of the conversation list.

### How can you reproduce the bug?
have an inbox with more than one page (8+) of conversations, go into a DM with the last one, then press back.

**Comment by killthebuddh4** [comment]
@matejcsok-ee @Aaron-EE I think we probably want to just store the scroll state in a zustand store and read from the store when we mount the component. Or some other similar solution.
