### ISSUE TITLE
New Message Screen -> ENS resolution and defunct + button

### ISSUE THREAD

**Issue by seanrelay** [relaycc/relay#388]
### Describe the bug. Include a video.
https://www.loom.com/share/80bd31d32fbe40629b4e6cb149006a60

1) Long address when resolving ENS name instead of the name searched for
2) The + button does nothing, user has to know to press enter. Recommend counting them entering .eth as "enter"

### What is the expected behavior?
When searching for an ENS name, I suddenly see a long address that I have no way of knowing is correct or not. I should see the ENS name I searched for. 

### What is the actual behavior?
Shows a 0xaddress with a ... oddly in the back half. 

### How can you reproduce the bug?
Start a new message with vdp.eth

**Comment by killthebuddh4** [comment]
@seanrelay Are we sure we want to show the ENS name? It seems like if you're entering an ENS name you would want to see the address that it resolves to. 

@matejcsok-ee @Aaron-EE Please implement a fix for the broken "+" button but wait to see what we want to do with the ENS name.

**Comment by seanrelay** [comment]
You'll see that 0x address after the first message to them. 

When messaging an ENS name you'll likely have 0 knowledge of what 0x address it should be. 

I think it's a good confirmation to the user that they entered the right ENS by showing avatar + ENS name (+0xaddress if we want to triple confirm)

**Comment by Aaron-EE** [comment]
@killthebuddh4 Should we implement @seanrelay s solution?

**Comment by killthebuddh4** [comment]
> @killthebuddh4 Should we implement @seanrelay s solution?

Yes please.
