### ISSUE TITLE
*Mobile* Hard to tell whose profile you are on when searching and switching

### ISSUE THREAD

**Issue by BrianS111** [relaycc/relay#39]
https://user-images.githubusercontent.com/81312527/194627891-2fe350a1-7fd2-4007-83ad-62a0870d54b2.mov

This is the view I get from my phone, nothing changes when switching to notify you whose profile you are on except the address bar. 

Solutions to this might be a responsive header of the profile page you are on? Or the name showing on each card? 

This might be a separate Issue.. but in the Metamask browser the URL doesn't change to the profile's name. But this might be a non-issue if a solution is implemented for what was mentioned above

**Comment by BrianS111** [comment]
@killthebuddh4 @vdp.eth @seandaopanel just tagging you guys for opinions as I'm not 100% sure what we want to do here, if anything.

**Comment by seandaopanel** [comment]
The short/medium-term fix is https://github.com/relaycc/relay/issues/15 
The instant fix would be a some "search success" alert to the user? or a responsive header

**Comment by BrianS111** [comment]
I would think responsive header is the way to go.. Makes it look more like a 'Profile' than some search result that may or may not have happened.

**Comment by killthebuddh4** [comment]
> I would think responsive header is the way to go.. Makes it look more like a 'Profile' than some search result that may or may not have happened.

What would be included in the responsive header?

**Comment by BrianS111** [comment]
Very short term, a H1 below the searchbox that says killthebuddha.eth or whoever you searched for

**Comment by killthebuddh4** [comment]
Ok I think I know what to do and/or can do this super fast, so I'm gonna just do it right now.

**Comment by killthebuddh4** [comment]
Longer term, #15 does solve this.
