### ISSUE TITLE
When I send a message it should skip requests and go to inbox

### ISSUE THREAD

**Issue by seanrelay** [relaycc/relay#390]
### Describe the bug. Include a video.
https://www.loom.com/share/9b6ef2f4ccd34f97be830b2681677d42

### What is the expected behavior?
Anytime I message or respond to an address, it should be in my inbox and not requests. 

### What is the actual behavior?
All messages go to requests

### How can you reproduce the bug?
Message a new address and it will be in requests.

**Comment by seanrelay** [comment]
This one will confuse 100% of users

**Comment by killthebuddh4** [comment]
@matejcsok-ee https://www.loom.com/share/25192a99318244f6ad98c00182f7c74b
