### ISSUE TITLE
LENS card goes to lenster and LENSTER card grey

### ISSUE THREAD

**Issue by andrewvdp** [relaycc/relay#4]
got to https://relay.cc/u/seanwbren.eth an connect wallet.
On the LENS card the link will take you to LENSTER
On the LENSTER card the link is greyed out

**Comment by seandaopanel** [comment]
Notion "Active Cards" page has correct links for Lens, Lenster, and Lenstube

**Comment by seandaopanel** [comment]
this was fixed.

**Comment by killthebuddh4** [comment]
> this was fixed.

This bug still exists.

**Comment by killthebuddh4** [comment]
I think this shows the bug, unless I'm misunderstanding:

https://user-images.githubusercontent.com/100799178/194387298-8f2da119-afed-4c9f-b652-e48195644545.mov

**Comment by seandaopanel** [comment]
Whoops, thought it was fixed when it wasn't. For the Lens link, they made lensfrens.xyz but it's inferior to lenster, and it seems they're recommending it over their own demo site.

**Comment by seandaopanel** [comment]
So I think this ticket would be complete by adding the lenster and lenstube correct links, which are in the Notion product page for Profiles.

**Comment by seandaopanel** [comment]
@killthebuddh4 we're talking to Lens people, we should fix these links asap

**Comment by BrianS111** [comment]
I'll work on it in about 30 min and see if it's an easy fix or an achilles thing

**Comment by BrianS111** [comment]
I accidentally hit the 3 button btw
