### ISSUE TITLE
One card column layout

### ISSUE THREAD

**Issue by BrianS111** [relaycc/relay#40]
This is a design opinion, but IMO when the cards get to one column, the alignment should be perfect with the rest of the site. Similar to this two column layout. 
![0032D8F6-1346-4BBF-BAFB-5E83C8A3DB4A](https://user-images.githubusercontent.com/81312527/194653027-233010a1-4593-4578-9ecf-f6a03f33572a.jpeg)

The alignment doesn't work here, and the best solution I can think of is expanding everything as wide as possible in the 1 card column layout with some padding around the sides so it takes up the same space as the two card layout and what not

![1863168D-3DFB-4340-955C-F5BA75DCEBDA](https://user-images.githubusercontent.com/81312527/194653269-32284fb0-966f-446b-b485-d78fd7e39f0e.jpeg)

**Comment by BrianS111** [comment]
![261AB817-C9D2-4482-8883-99B1A34FED98](https://user-images.githubusercontent.com/81312527/194653522-69780f8b-afe7-4e2e-97e4-7283234b0141.jpeg)

Something similar to this

**Comment by killthebuddh4** [comment]
I agree with this ticket but I'm going to close it for now because it will almost certainly get pulled into other planned tickets.
