### ISSUE TITLE
Update content for Google search result

### ISSUE THREAD

**Issue by BrianS111** [relaycc/relay#43]
![A50F8D51-F289-4C74-827C-9F760D6BD845_4_5005_c](https://user-images.githubusercontent.com/81312527/196547850-0eca6bbe-d8cb-471c-9a93-5ba9d2ec9142.jpeg)
This is what relaycc shows up as now with google searches. We need content to put there using the Head component with Next JS. I can get this done once I know what to write in its place @seandaopanel

**Comment by killthebuddh4** [comment]
Try to make it look like this:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/100799178/197035134-4ab53632-38d0-4012-ab81-5bf2203bd0df.png">

* Description: "Relay is the web3 crossroads. Decentralized, secure, and private identity and messaging."
* Links: relay.cc/u/relaycc.eth and whoever @seandaopanel decides.

**Comment by killthebuddh4** [comment]
@BrianS111 The profile links to add:
relaycc.eth seanwbren.eth nader.lens petermdenton.eth
