### ISSUE TITLE
Remove deprecated testnets from network switch

### ISSUE THREAD

**Issue by andrewvdp** [relaycc/relay#5]
After the merge, a lot of testnets are deprecated. We should remove them as options in the network switch in the top right.

**Comment by killthebuddh4** [comment]
@andrewvdp Please update with specifics, which networks should be removed? Are they deprecated immediately or at some future date?

**Comment by andrewvdp** [comment]
Alchemy is going to deprecate these networks tomorrow (10/5):
Rinkeby, Ropsten, Kovan, Arb Rinkeby, and Opt Kovan

**Comment by BrianS111** [comment]
https://github.com/relaycc/relay/pull/44
