### ISSUE TITLE
relay.cc/ home page update

### ISSUE THREAD

**Issue by seanrelay** [relaycc/relay#51]
The home page structure for relay.cc should become: 

Header - keep the same
- - - - - - - - - - - - - - - - - - - - - - - - - - - 
<profile card row that entices them to sign in>
-Show the current top tow of relay.cc 
<img width="1373" alt="Screen Shot 2022-10-28 at 10 47 44 AM" src="https://user-images.githubusercontent.com/102389629/198700131-939e15d5-40a2-47f5-b635-031f88a39841.png">
- Make the 5 emoticon cards 50% more transparent

- - - - - - - - - - - - - - - - - - - - - - - - - - - 

<Relay, ENS, POAP, Opensea, Snapshot, Soundxyz card row>

- - - - - - - - - - - - - - - - - - - - - - - - - - - 

Lens section with 12cards in 2 rows
- - - - - - - - - - - - - - - - - - - - - - - - - - - 

the rest of the current apps except DID

- - - - - - - - - - - - - - - - - - - - - - - - - - - 

DID apps (the current last 12) 
<img width="1368" alt="Screen Shot 2022-10-28 at 10 57 36 AM" src="https://user-images.githubusercontent.com/102389629/198701843-b0241bd2-67ab-4296-b8c7-ed13801f233b.png">

- - - - - - - - - - - - - - - - - - - - - - - - - - - 
Footer - take structure from try.relay.cc
<img width="936" alt="Screen Shot 2022-10-28 at 10 56 42 AM" src="https://user-images.githubusercontent.com/102389629/198701720-b0dc666e-4a7c-4f92-bfe7-e4055dd3c8e2.png">

Note for Divider design: 
- - - - - - - - - - - - - - - - - - - - - - - - - - - 
^ this means a section divider, which can be a thin purple line (same purple as logo).

**Comment by seanrelay** [comment]
For EthSF week, it'd be great to have a small update done by 11/2 to be: 

Header - keep the same
- - - - - - - - - - - - - - - - - - - - - - - - - - - 
<profile card row that entices them to sign in>
-Show the current top tow of relay.cc 
<img width="1373" alt="Screen Shot 2022-10-28 at 10 47 44 AM" src="https://user-images.githubusercontent.com/102389629/198700131-939e15d5-40a2-47f5-b635-031f88a39841.png">
- Make the 5 emoticon cards 50% more transparent


- - - - - - - - - - - - - - - - - - - - - - - - - - - 


<Relay, ENS, POAP, Opensea, Snapshot, Soundxyz card row>


- - - - - - - - - - - - - - - - - - - - - - - - - - - 

Lens section with 12cards in 2 rows
- - - - - - - - - - - - - - - - - - - - - - - - - - - 


the rest of the current apps

**Comment by seanrelay** [comment]
The cards need 4 small changes to the hover-state. 
<img width="215" alt="Screen Shot 2022-10-28 at 11 03 24 AM" src="https://user-images.githubusercontent.com/102389629/198703044-90aadd71-2871-4b0d-8c97-a762df20f330.png">

1. As this is the home page for a user, it doesn't make sense to have "Send a Message" on every card so remove that. 
1a. Instead, change to say "Visit App" and have a link to the site homepage (same as where the logo links)
2. Change the ""View on ___" button to say "View Profile", same link as current.
2a.If no wallet connected, make the "View Profile" greyed out and unclickable.

**Comment by seanrelay** [comment]
The sections can reveal (and hide) more cards like the section selectors in https://light.so/seanwbren.eth

**Comment by andrewvdp** [comment]
@seanrelay 
If the goal is to make it so that you don't need a connected wallet in order to view someone's profile should this still be done?
```
- Make the 5 emoticon cards 50% more transparent
```

**Comment by seanrelay** [comment]
@andrewvdp this can be removed

**Comment by andrewvdp** [comment]
@seanrelay 
We should also have a fixed launch receiver button in the bottom right correct?

**Comment by andrewvdp** [comment]
We are going to have categories at the top of the page. So instead it is going to look like:
HEADER
All Categories  Web3   Lens   Networked Identity   Music   Impact DAOs    DeFi    DAOs   Farcaster   ZK
-------------------------------------------------------------------------------------------------------
- Card view with currently selected category. 
- six cards per row
- after the first rows there is a "view more" button in the center to load another 12 cards
 -------------------------------------------------------------------------------------------------------
Footer

**Comment by seanrelay** [comment]
Two things
1) let's try not having a view more button, and instead always show all cards in a category. 
2)  We don't need an "all categories"  

edited version:
> ```
> HEADER
> 
>  Popular  Lens  Music  Identity  DAOs  Farcaster ZK ImpactDAOs  DAO Tools
> -------------------------------------------------------------------------------------------------------
> - Card view with currently selected category. 
> - six cards per row

> -------------------------------------------------------------------------------------------------------
> 
> FOOTER
> ```

**Comment by BrianS111** [comment]
@seanwbren @andrewvdp Right now the cards are set to stay at the same size no matter what, so -six cards per row would require the cards changing in size to fit the width of the screen. Currently the bigger / smaller the window gets, the more or less cards there are per row. Do we want to try to go with a setup to always have 6 cards per row and the cards themselves change in size?

**Comment by seanrelay** [comment]
@BrianS111 Keep the current functionality that the video shows (less number of cards per row when width is smaller).

I think we do have to think about mobile screens and smaller cards, but not yet.
