### ISSUE TITLE
Description view on app cards.

### ISSUE THREAD

**Issue by killthebuddh4** [relaycc/relay#64]
Context:
* Each app card represents a project
* App cards don't have any information about a project except the name and logo

Feature:
* Add a longish (up to 2 sentences) project description to app cards

Notes/Options:

* The project description probably won't fit into the current default app card view (or maybe it would?):
<img width="284" alt="image" src="https://user-images.githubusercontent.com/100799178/206968757-205521f4-ff85-4f2e-ac6d-7c8f2e5118bc.png">

* In theory we _could_ make the name and logo smaller but that's not the first option we want to try.
* Instead, let's try to include some kind of show/hide functionality.
  * a button that toggles the whole card into a "more info" view or 
  * a hover/long-press state 
  * a button that squishes elements in the current default view and expands some text

**Comment by seanrelay** [comment]
Let's do "a button that toggles the whole card into a "more info" view" 

On the Lenstube card, if we add an "INFO" button that appears on the top-right on hover (or always there on mobile)

When clicked, the card switches/morphs to a tiny logo in the top right, small name under that, and description takes up the whole center of the card.  Everything else remains the same.

**Comment by BrianS111** [comment]
And if the user clicks info, description comes up... Then they take their mouse off the card and it goes back to how it is shown in the photo above?

**Comment by seanrelay** [comment]
I think it could/should be a toggle on the "INFO" button

**Comment by BrianS111** [comment]
https://user-images.githubusercontent.com/81312527/207375710-8787e04d-7d7b-4f82-a047-c0fd59d8842e.mov

Small update on the info button to see if this is the look we are going for

**Comment by seanrelay** [comment]
> B16319E1-F525-4060-A083-95087400507C.mov 
> 
> Small update on the info button to see if this is the look we are going for

That is what I imagined. The border spacing not being the same as the bottom buttons looks a little off.

**Comment by seanrelay** [comment]
but looks functional and good

**Comment by BrianS111** [comment]
Yeah I was concerned about the alignment also. It's that way so it doesn't collide with the image. Ways I can go about fixing it are to move the image down, make the image smaller, or make the bottom buttons closer to the edge like the info button is displayed in that pic. I'll find something that looks good though
