### ISSUE TITLE
Add animations when users search for a new profile

### ISSUE THREAD

**Issue by BrianS111** [relaycc/relay#7]
* opinion *
It isn't very clear what's happening when using the search bar. It took me ~3 minutes to realize it wasn't actually broken. 
Nothing happens on the screen besides the changing of the text in the second and third buttons which I didn't notice at first.

Possible simple fix without any huge adjustment to the site would be an animation on the cards that change after search (something like a transform scale 0% 1 ///  50% 1.1 /// 100% 1  animation) or what ever framer uses to pulse. There are other ways to handle it, that's just the first thing I thought of.. Maybe a border color change for 500ms? IDK but something to make it more obvious as to what and if anything changed after searching would be beneficial.

**Comment by killthebuddh4** [comment]
* Copy the rendering animation from the conversations list (the one where each cards fades in right after the previous card)
* So the user hits enter, and that animation is triggered across the whole list of cards.

**Comment by BrianS111** [comment]
https://user-images.githubusercontent.com/81312527/199337606-bae9f607-c0eb-46d1-9872-0db3e952a20a.mov

Posting the before video here for future reference
