### ISSUE TITLE
Urgent 404 Bug

### ISSUE THREAD

**Issue by bribren7** [relaycc/relay#79]
Drew and I had the same issue where if you search someone's ENS name from the search bar on relay.cc it gives you a 404 page error. Tried it out with lens name and eth address and it also resulted in a 404 bug.

**Comment by killthebuddh4** [comment]
Fixed. Instead of attempting to navigate to a different page (which was actually just the exact same page at a different URL), and then opening Receiver, it just opens Receiver.
