### ISSUE TITLE
When not connected to a wallet users should be prompted to do so when clicking 'send message' 

### ISSUE THREAD

**Issue by BrianS111** [relaycc/relay#8]
When not connected to a wallet I think the user should be prompted to do so when clicking the buttons on the cards. Otherwise it makes it seem like they can't really do anything with the website, and they might not realize they have to connect to have more functionality. 

https://user-images.githubusercontent.com/81312527/193326785-8c44e40c-51ef-4184-ab8a-f29ffe755613.mov

**Comment by killthebuddh4** [comment]
This ticket went stale because the profile page was moved to `/u/0xADDRESS` so you don't need to connect a wallet for the buttons to be enabled.
